/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2018 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package ti.bottomsheet;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;

import org.appcelerator.kroll.common.TiConfig;

@Kroll.module(name="TitaniumAndroidBottomSheet", id="ti.bottomsheet")
public class TitaniumAndroidBottomSheetModule extends KrollModule
{
	// Standard Debugging variables
	private static final String LCAT = "TitaniumAndroidBottomSheetModule";
	private static final boolean DBG = TiConfig.LOGD;

	public TitaniumAndroidBottomSheetModule()
	{
		super();
	}
}

